name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  npm_security_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Run npm security tests
      run: npm audit

  integration_tests:
    runs-on: ubuntu-latest
    needs: npm_security_tests
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Start app
      run: npm start &
    - name: Run integration tests
      run: npm test
  
  deploy_render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: integration_tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}