name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  npm_security_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Run npm security tests
      run: npm audit

  integration_tests:
    runs-on: ubuntu-latest
    needs: npm_security_tests
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Start app
      run: npm start &
    - name: Run integration tests
      run: npm test
